const fs = require('fs');
const text = fs.readFileSync('backend/src/controllers/superadminController.js', 'utf8');
const fnStart = text.indexOf('exports.createDeliveryPartner = async (req, res) =>');
if(fnStart === -1) throw new Error('createDeliveryPartner not found');
const paramsMatch = text.slice(fnStart).match(/const params = \[([\s\S]*?)\];/);
if(!paramsMatch) throw new Error('params block not found');
const paramsRaw = paramsMatch[1];
const params = paramsRaw.split(',').map(s=>s.trim()).filter(Boolean);
const colsMatch = text.slice(fnStart).match(/const cols = `([\s\S]*?)`;/);
if(!colsMatch) throw new Error('cols block not found');
const colsTemplate = colsMatch[1];
const colsFunc = new Function('approved_by_id','approved_by_user_id','approved_by_name','approved_by_email','return `' + colsTemplate.replace(/`/g, '\\`') + '`;');
const colsNull = colsFunc(null,'x','x','x').split(',').map(s=>s.trim()).filter(Boolean);
const colsNotNull = colsFunc(1,'x','x','x').split(',').map(s=>s.trim()).filter(Boolean);
console.log('params len', params.length);
console.log('cols len (approved_by_id null)', colsNull.length);
console.log('cols len (approved_by_id 1)', colsNotNull.length);
console.log('params tail', params.slice(-10));
console.log('cols tail null', colsNull.slice(-10));
console.log('cols tail notnull', colsNotNull.slice(-12));
