const fs = require('fs');
const text = fs.readFileSync('src/controllers/superadminController.js', 'utf8');
const funcStart = text.indexOf('exports.createHomeChef');
const funcEnd = text.indexOf('exports.updateHomeChef', funcStart);
const funcText = funcEnd === -1 ? text.slice(funcStart) : text.slice(funcStart, funcEnd);
const execPos = funcText.indexOf('await pool.execute(');
const qStart = funcText.indexOf('`', execPos);
const qEnd = funcText.indexOf('`', qStart + 1);
const query = funcText.slice(qStart + 1, qEnd);
const valuesStart = query.indexOf('VALUES (');
const valuesText = query.slice(valuesStart + 'VALUES ('.length, query.lastIndexOf(')'));
const lines = valuesText.split('\n');
let total = 0;
console.log('------ VALUES LINES ------');
lines.forEach((line, idx) => {
  const count = (line.match(/\?/g) || []).length;
  total += count;
  console.log(idx, count, line.replace(/\t/g,' ').trim());
});
console.log('TOTAL ? in VALUES', total);
