const fs = require('fs');
const mysql = require('mysql2/promise');
(async () => {
  const text = fs.readFileSync('src/controllers/superadminController.js', 'utf8');
  const insertStart = text.indexOf('INSERT INTO home_chefs (');
  if (insertStart === -1) return console.error('INSERT NOT FOUND');
  const valuesPos = text.indexOf(') VALUES', insertStart);
  const columnsText = text.slice(insertStart + 'INSERT INTO home_chefs ('.length, valuesPos).trim();
  const columns = columnsText.split(/,\s*(?=[^\)]*(?:\(|$))/).map(s => s.trim()).filter(Boolean);
  console.log('insert columns count', columns.length);
  console.log(columns.slice(0, 10));
  console.log('...');
  console.log(columns.slice(-10));
  const conn = await mysql.createConnection({ host: 'localhost', user: 'root', password: '', database: 'veetu_rusi' });
  const [rows] = await conn.execute('SHOW COLUMNS FROM home_chefs');
  const colNames = rows.map(r => r.Field);
  const missing = columns.filter(col => !colNames.includes(col));
  const extra = colNames.filter(col => !columns.includes(col));
  console.log('missing columns', missing);
  console.log('extra db columns not in insert', extra.slice(0, 20));
  await conn.end();
})();